### ISSUE TITLE
Error 1.21.1 (purpur)

### ISSUE THREAD

**Issue by levitskyyy** [wleka/AntiElytra#1]
# Console logs

```
[10:24:57 ERROR]: Could not pass event PlayerMoveEvent to AntiElytra v1.4.2-SNAPSHOT
java.lang.IllegalArgumentException: message cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:387) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.craftbukkit.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:382) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.craftbukkit.entity.CraftPlayer.sendMessage(CraftPlayer.java:399) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at AntiElytra v1.4.2.jar/org.example.abs.antielytra.AElytra_Event.disableElytra(AElytra_Event.java:34) ~[AntiElytra v1.4.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1624) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:75) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
antielytra reload
```

**Comment by dscss1** [comment]
Use my [fork  ](https://productionresultssa4.blob.core.windows.net/actions-results/120cac3a-5bce-45a4-a621-543c9b8f0a61/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/artifacts/314ae71b8c8dc9c952f0ffc58e35e6d9a41b5cf4756471c7cab0c9476cd5d20b.zip?rscd=attachment%3B+filename%3D%22Artifacts.zip%22&se=2025-02-02T15%3A15%3A30Z&sig=praDQY1r0Twnetru9U6ZDtCbnGm6o1Ei1uxtDpj3zsc%3D&ske=2025-02-03T01%3A10%3A42Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-02-02T13%3A10%3A42Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-02-02T15%3A05%3A25Z&sv=2025-01-05)
